[tool.black]
line-length = 100
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip_glob = ["*/migrations/*", "*/venv/*"]

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true  # M치s estricto: requiere type hints en todas las definiciones
disallow_incomplete_defs = true  # M치s estricto: requiere type hints completos
check_untyped_defs = true
disallow_untyped_decorators = true  # M치s estricto: requiere type hints en decoradores
no_implicit_optional = true
strict_optional = true
warn_redundant_casts = true  # Nuevo: advierte sobre conversiones redundantes
warn_unused_ignores = true  # Nuevo: advierte sobre ignores no utilizados
warn_no_return = true  # Nuevo: advierte sobre funciones sin return
warn_unreachable = true  # Nuevo: advierte sobre c칩digo inalcanzable

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false
disallow_incomplete_defs = false

[[tool.mypy.overrides]]
module = [
    "flask_sqlalchemy.*",
    "flask_migrate.*",
    "flask_marshmallow.*",
    "marshmallow_sqlalchemy.*",
    "facebook_business.*",
    "google_ads.*",
    "google.generativeai.*",
    "celery.*",
    "redis.*",
    "faker.*"
]
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"
python_classes = "Test*"
addopts = "--cov=adflux --cov-report=term-missing --cov-report=xml:coverage.xml"
