"""Add external_ids to Campaign and remove Meta fields

Revision ID: a2d2c9206410
Revises: e8c30a0e1c82
Create Date: 2025-04-02 16:25:20.001974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d2c9206410'
down_revision = 'e8c30a0e1c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_ids', sa.JSON(), nullable=True))
        batch_op.drop_column('external_ad_set_id')
        batch_op.drop_column('external_audience_id')
        batch_op.drop_column('external_ad_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_ad_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('external_audience_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('external_ad_set_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('external_ids')

    # ### end Alembic commands ###
