"""Initial schema based on current models

Revision ID: e8c30a0e1c82
Revises: 
Create Date: 2025-04-01 22:52:34.984065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c30a0e1c82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_openings',
    sa.Column('job_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('required_skills', sa.JSON(), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('target_segments', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('meta_campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('objective', sa.String(), nullable=True),
    sa.Column('effective_status', sa.String(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('stop_time', sa.DateTime(), nullable=True),
    sa.Column('daily_budget', sa.String(), nullable=True),
    sa.Column('lifetime_budget', sa.String(), nullable=True),
    sa.Column('budget_remaining', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('daily_budget', sa.Integer(), nullable=True),
    sa.Column('job_opening_id', sa.String(length=50), nullable=True),
    sa.Column('target_segment_ids', sa.JSON(), nullable=True),
    sa.Column('primary_text', sa.String(length=200), nullable=True),
    sa.Column('headline', sa.String(length=40), nullable=True),
    sa.Column('link_description', sa.String(length=50), nullable=True),
    sa.Column('creative_image_filename', sa.String(length=255), nullable=True),
    sa.Column('external_campaign_id', sa.String(length=255), nullable=True),
    sa.Column('external_ad_set_id', sa.String(length=255), nullable=True),
    sa.Column('external_ad_id', sa.String(length=255), nullable=True),
    sa.Column('external_audience_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_opening_id'], ['job_openings.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_external_campaign_id'), ['external_campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_status'), ['status'], unique=False)

    op.create_table('candidates',
    sa.Column('candidate_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('education_level', sa.String(length=50), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('primary_skill', sa.String(length=100), nullable=True),
    sa.Column('desired_salary', sa.Integer(), nullable=True),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidates_segment_id'), ['segment_id'], unique=False)

    op.create_table('meta_ad_sets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('effective_status', sa.String(), nullable=True),
    sa.Column('daily_budget', sa.String(), nullable=True),
    sa.Column('lifetime_budget', sa.String(), nullable=True),
    sa.Column('budget_remaining', sa.String(), nullable=True),
    sa.Column('optimization_goal', sa.String(), nullable=True),
    sa.Column('billing_event', sa.String(), nullable=True),
    sa.Column('bid_amount', sa.String(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['meta_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=50), nullable=False),
    sa.Column('candidate_id', sa.String(length=50), nullable=False),
    sa.Column('application_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job_openings.job_id'], ),
    sa.PrimaryKeyConstraint('application_id'),
    sa.UniqueConstraint('job_id', 'candidate_id', name='uq_job_candidate_application')
    )
    op.create_table('meta_ads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('effective_status', sa.String(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('creative_id', sa.String(), nullable=True),
    sa.Column('creative_details', sa.JSON(), nullable=True),
    sa.Column('ad_set_id', sa.String(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ad_set_id'], ['meta_ad_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_insights',
    sa.Column('object_id', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_stop', sa.Date(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('spend', sa.Float(), nullable=True),
    sa.Column('cpc', sa.Float(), nullable=True),
    sa.Column('cpm', sa.Float(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('cpp', sa.Float(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('unique_clicks', sa.Integer(), nullable=True),
    sa.Column('unique_ctr', sa.Float(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=True),
    sa.Column('action_values', sa.JSON(), nullable=True),
    sa.Column('submit_applications', sa.Integer(), nullable=True),
    sa.Column('submit_applications_value', sa.Float(), nullable=True),
    sa.Column('leads', sa.Integer(), nullable=True),
    sa.Column('leads_value', sa.Float(), nullable=True),
    sa.Column('view_content', sa.Integer(), nullable=True),
    sa.Column('view_content_value', sa.Float(), nullable=True),
    sa.Column('meta_campaign_id', sa.String(), nullable=True),
    sa.Column('meta_ad_set_id', sa.String(), nullable=True),
    sa.Column('meta_ad_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meta_ad_id'], ['meta_ads.id'], ),
    sa.ForeignKeyConstraint(['meta_ad_set_id'], ['meta_ad_sets.id'], ),
    sa.ForeignKeyConstraint(['meta_campaign_id'], ['meta_campaigns.id'], ),
    sa.PrimaryKeyConstraint('object_id', 'level', 'date_start')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meta_insights')
    op.drop_table('meta_ads')
    op.drop_table('applications')
    op.drop_table('meta_ad_sets')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_segment_id'))

    op.drop_table('candidates')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_status'))
        batch_op.drop_index(batch_op.f('ix_campaigns_platform'))
        batch_op.drop_index(batch_op.f('ix_campaigns_external_campaign_id'))

    op.drop_table('campaigns')
    op.drop_table('segments')
    op.drop_table('meta_campaigns')
    op.drop_table('job_openings')
    # ### end Alembic commands ###
